language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm i

script:
  - npm run build

after_success:
  - tar czf build-prod.tar.gz dist

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build-prod.tar.gz
  skip_cleanup: true
  on:
    tags: true
