language: node_js
node_js:
  - "8"

branches:
  only:
    - master

script:
  - npm run build

after_success:
  - tar czf dist.tar.gz dist

before_deploy:
  - git tag "$(date +'%Y-%m-%d-%H-%M-%S')"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist.tar.gz
  skip_cleanup: true
  on:
    repo: entwico/helm-deployer-fe
    all_branches: true
